# This is a Flutter iOS Podfile configured for Codemagic builds
platform :ios, '13.0'

# Use static frameworks to avoid 'Pods_Runner' dynamic linkage issues
use_frameworks! :linkage => :static
use_modular_headers!

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

flutter_root = File.expand_path(File.join('..', 'Flutter'))
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

target 'Runner' do
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      # Ensure modules enabled for Swift/ObjC interop
      config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
    end
  end
  flutter_additional_ios_build_settings(installer)
end
